insert into Departments (did, dname) values (1, 'Engineering');
insert into Departments (did, dname) values (2, 'Business Development');
insert into Departments (did, dname) values (3, 'Human Resources');
insert into Departments (did, dname) values (4, 'Research and Development');
insert into Departments (did, dname) values (5, 'Accounting');
insert into Departments (did, dname) values (6, 'Marketing');
insert into Departments (did, dname) values (7, 'Sales');
insert into Departments (did, dname) values (8, 'Support');
insert into Departments (did, dname) values (9, 'Product Management');
insert into Departments (did, dname) values (10, 'Legal');
insert into Departments (did, dname) values (11, 'Services');
insert into Departments (did, dname) values (12, 'Training');
